/* eslint-disable camelcase */
import languages from '../../languages/ISO639LangCodesList';

const LANGUAGES_MAP = {
	ace_Arab: 'Acehnese (Arabic script)',
	ace_Latn: 'Acehnese (Latin script)',
	afr_Latn: 'Afrikaans',
	aka_Latn: 'Akan',
	amh_Ethi: 'Amharic',
	hye_Armn: 'Armenian',
	asm_Beng: 'Assamese',
	ast_Latn: 'Asturian',
	awa_Deva: 'Awadhi',
	quy_Latn: 'Ayacucho Quechua',
	ban_Latn: 'Balinese',
	bam_Latn: 'Bambara',
	bjn_Arab: 'Banjar (Arabic script)',
	bjn_Latn: 'Banjar (Latin script)',
	bak_Cyrl: 'Bashkir',
	eus_Latn: 'Basque',
	bel_Cyrl: 'Belarusian',
	bem_Latn: 'Bemba',
	ben_Beng: 'Bengali',
	bho_Deva: 'Bhojpuri',
	bos_Latn: 'Bosnian',
	bug_Latn: 'Buginese',
	bul_Cyrl: 'Bulgarian',
	mya_Mymr: 'Burmese',
	cat_Latn: 'Catalan',
	ceb_Latn: 'Cebuano',
	tzm_Tfng: 'Central Atlas Tamazight',
	ayr_Latn: 'Central Aymara',
	knc_Arab: 'Central Kanuri (Arabic script)',
	knc_Latn: 'Central Kanuri (Latin script)',
	ckb_Arab: 'Central Kurdish',
	hne_Deva: 'Chhattisgarhi',
	zho_Hans: 'Chinese (Simplified)',
	zho_Hant: 'Chinese (Traditional)',
	cjk_Latn: 'Chokwe',
	crh_Latn: 'Crimean Tatar',
	hrv_Latn: 'Croatian',
	ces_Latn: 'Czech',
	dan_Latn: 'Danish',
	prs_Arab: 'Dari',
	nld_Latn: 'Dutch',
	dyu_Latn: 'Dyula',
	dzo_Tibt: 'Dzongkha',
	pan_Guru: 'Eastern Panjabi',
	ydd_Hebr: 'Eastern Yiddish',
	arz_Arab: 'Egyptian Arabic',
	eng_Latn: 'English',
	epo_Latn: 'Esperanto',
	est_Latn: 'Estonian',
	ewe_Latn: 'Ewe',
	fao_Latn: 'Faroese',
	fij_Latn: 'Fijian',
	fin_Latn: 'Finnish',
	fon_Latn: 'Fon',
	fra_Latn: 'French',
	fur_Latn: 'Friulian',
	glg_Latn: 'Galician',
	lug_Latn: 'Ganda',
	kat_Geor: 'Georgian',
	deu_Latn: 'German',
	ell_Grek: 'Greek',
	grn_Latn: 'Guarani',
	guj_Gujr: 'Gujarati',
	hat_Latn: 'Haitian Creole',
	khk_Cyrl: 'Halh Mongolian',
	hau_Latn: 'Hausa',
	heb_Hebr: 'Hebrew',
	hin_Deva: 'Hindi',
	hun_Latn: 'Hungarian',
	isl_Latn: 'Icelandic',
	ibo_Latn: 'Igbo',
	ilo_Latn: 'Ilocano',
	ind_Latn: 'Indonesian',
	gle_Latn: 'Irish',
	ita_Latn: 'Italian',
	jpn_Jpan: 'Japanese',
	jav_Latn: 'Javanese',
	kac_Latn: 'Jingpho',
	kbp_Latn: 'Kabiyè',
	kea_Latn: 'Kabuverdianu',
	kab_Latn: 'Kabyle',
	kam_Latn: 'Kamba',
	kan_Knda: 'Kannada',
	kas_Arab: 'Kashmiri (Arabic script)',
	kas_Deva: 'Kashmiri (Devanagari script)',
	kaz_Cyrl: 'Kazakh',
	khm_Khmr: 'Khmer',
	kon_Latn: 'Kikongo',
	kik_Latn: 'Kikuyu',
	kmb_Latn: 'Kimbundu',
	kin_Latn: 'Kinyarwanda',
	kor_Hang: 'Korean',
	kir_Cyrl: 'Kyrgyz',
	lao_Laoo: 'Lao',
	ltg_Latn: 'Latgalian',
	lij_Latn: 'Ligurian',
	lim_Latn: 'Limburgish',
	lin_Latn: 'Lingala',
	lit_Latn: 'Lithuanian',
	lmo_Latn: 'Lombard',
	lua_Latn: 'Luba-Kasai',
	luo_Latn: 'Luo',
	ltz_Latn: 'Luxembourgish',
	mkd_Cyrl: 'Macedonian',
	mag_Deva: 'Magahi',
	mai_Deva: 'Maithili',
	mal_Mlym: 'Malayalam',
	mlt_Latn: 'Maltese',
	mri_Latn: 'Maori',
	mar_Deva: 'Marathi',
	mni_Beng: 'Meitei (Bengali script)',
	acm_Arab: 'Mesopotamian Arabic',
	min_Arab: 'Minangkabau (Arabic script)',
	min_Latn: 'Minangkabau (Latin script)',
	lus_Latn: 'Mizo',
	arb_Latn: 'Modern Standard Arabic (Romanized)',
	arb_Arab: 'Modern Standard Arabic',
	ary_Arab: 'Moroccan Arabic',
	mos_Latn: 'Mossi',
	ars_Arab: 'Najdi Arabic',
	npi_Deva: 'Nepali',
	fuv_Latn: 'Nigerian Fulfulde',
	azj_Latn: 'North Azerbaijani',
	apc_Arab: 'North Levantine Arabic',
	kmr_Latn: 'Northern Kurdish',
	nso_Latn: 'Northern Sotho',
	uzn_Latn: 'Northern Uzbek',
	nob_Latn: 'Norwegian Bokmål',
	nno_Latn: 'Norwegian Nynorsk',
	nus_Latn: 'Nuer',
	nya_Latn: 'Nyanja',
	oci_Latn: 'Occitan',
	ory_Orya: 'Odia',
	pag_Latn: 'Pangasinan',
	pap_Latn: 'Papiamento',
	plt_Latn: 'Plateau Malagasy',
	pol_Latn: 'Polish',
	por_Latn: 'Portuguese',
	ron_Latn: 'Romanian',
	run_Latn: 'Rundi',
	rus_Cyrl: 'Russian',
	smo_Latn: 'Samoan',
	sag_Latn: 'Sango',
	san_Deva: 'Sanskrit',
	sat_Olck: 'Santali',
	srd_Latn: 'Sardinian',
	gla_Latn: 'Scottish Gaelic',
	srp_Cyrl: 'Serbian',
	shn_Mymr: 'Shan',
	sna_Latn: 'Shona',
	scn_Latn: 'Sicilian',
	szl_Latn: 'Silesian',
	snd_Arab: 'Sindhi',
	sin_Sinh: 'Sinhala',
	slk_Latn: 'Slovak',
	slv_Latn: 'Slovenian',
	som_Latn: 'Somali',
	azb_Arab: 'South Azerbaijani',
	ajp_Arab: 'South Levantine Arabic',
	pbt_Arab: 'Southern Pashto',
	sot_Latn: 'Southern Sotho',
	dik_Latn: 'Southwestern Dinka',
	spa_Latn: 'Spanish',
	lvs_Latn: 'Standard Latvian',
	zsm_Latn: 'Standard Malay',
	bod_Tibt: 'Standard Tibetan',
	sun_Latn: 'Sundanese',
	swh_Latn: 'Swahili',
	ssw_Latn: 'Swati',
	swe_Latn: 'Swedish',
	tgl_Latn: 'Tagalog',
	tgk_Cyrl: 'Tajik',
	taq_Latn: 'Tamasheq (Latin script)',
	taq_Tfng: 'Tamasheq (Tifinagh script)',
	tam_Taml: 'Tamil',
	tat_Cyrl: 'Tatar',
	acq_Arab: 'Ta’izzi-Adeni Arabic',
	tel_Telu: 'Telugu',
	tha_Thai: 'Thai',
	tir_Ethi: 'Tigrinya',
	tpi_Latn: 'Tok Pisin',
	als_Latn: 'Tosk Albanian',
	tso_Latn: 'Tsonga',
	tsn_Latn: 'Tswana',
	tum_Latn: 'Tumbuka',
	aeb_Arab: 'Tunisian Arabic',
	tur_Latn: 'Turkish',
	tuk_Latn: 'Turkmen',
	twi_Latn: 'Twi',
	ukr_Cyrl: 'Ukrainian',
	umb_Latn: 'Umbundu',
	urd_Arab: 'Urdu',
	uig_Arab: 'Uyghur',
	vec_Latn: 'Venetian',
	vie_Latn: 'Vietnamese',
	war_Latn: 'Waray',
	cym_Latn: 'Welsh',
	gaz_Latn: 'West Central Oromo',
	pes_Arab: 'Western Persian',
	wol_Latn: 'Wolof',
	xho_Latn: 'Xhosa',
	yor_Latn: 'Yoruba',
	yue_Hant: 'Yue Chinese',
	zul_Latn: 'Zulu',
};

// Cached map
let LANGUAGES_V1_TO_V2_MAP: Record<string, string> | null = null;

/**
 * Returns mapping ISO639-v1 languages to ISO639-v2 with suffix
 *
 * Example: `en -> eng_Latn`
 */
export const getLanguagesMap = () => {
	// Fill map
	if (LANGUAGES_V1_TO_V2_MAP === null) {
		LANGUAGES_V1_TO_V2_MAP = {};

		for (const key in LANGUAGES_MAP) {
			const v2Code = key.split('_')[0];
			const languageMap = languages.find(
				({ v2, v2B, v2T }) => v2 === v2Code || v2B === v2Code || v2T === v2Code,
			);

			if (languageMap && languageMap.v1) {
				LANGUAGES_V1_TO_V2_MAP[languageMap.v1] = key;
			}
		}
	}

	return LANGUAGES_V1_TO_V2_MAP;
};
